### ISSUE TITLE
204 Successes break the error checking

### ISSUE THREAD

**Issue by Charlesworth** [automata-tech/eva_python_sdk#32]
Some of the API endpoints have changed their successful status code from 200 to 204 and this isn't accounted for by the client, i.e. the reset errors endpoint. 204's will trigger an error exception while the request was actually a success. Thanks to @eeberhard  for finding the bug

**Comment by walker-j** [comment]
Endpoints which return 204 on success in v3.1.0 are: POST `control/reset_errors` , DELETE `auth`, POST `auth/renew`

**Comment by walker-j** [comment]
Fixed in #34
