### ISSUE TITLE
Add explicit check that SDK version is compatible

### ISSUE THREAD

**Issue by walker-j** [automata-tech/eva_python_sdk#45]
The `api_versions` method already exists on `EvaHTTPClient` class.

Perhaps move versioning spec out of the `README` and check against it when make `auth_create_session` calls?

**Comment by walker-j** [comment]
Issue #46 should be resolved before making this enhancement.

**Comment by tallpress** [comment]
https://github.com/automata-tech/eva_python_sdk/pull/74
