### ISSUE TITLE
Generated documentation

### ISSUE THREAD

**Issue by walker-j** [automata-tech/eva_python_sdk#48]
Use [pydoc](https://docs.python.org/3.8/library/pydoc.html)/[sphinx ](https://www.sphinx-doc.org/en/master/) or similar to generate documentation detailing the objects provided by this SDK.

The documentation could then be deployed to GitHub pages etc.

**Comment by tallpress** [comment]
https://github.com/automata-tech/eva_python_sdk/pull/75
