### ISSUE TITLE
`control_go_to` uses the wrong JSON arguments

### ISSUE THREAD

**Issue by LouisBrunner** [automata-tech/eva_python_sdk#49]
`control_go_to` currently accepts `duration` and `velocity` but the API excepts `time` and `max_speed` (https://automata.tech/docs/v/3.1.0/api/controls/#go-to).

While `duration` renamed `time` in the request body, `velocity` is kept as-is, triggering a 400.

We should rename `velocity` into `max_speed` completely (as it's broken anyway) and add `time` as well as `duration` to keep the function backward compatible.

**Comment by Charlesworth** [comment]
I figured I would just change the duration to time, as it's already a breaking change we'll have to update the SDK version anyway. Can also re-add duration as an additional backwards compat argument but not sure if we do that or just rip off the band-aid now? thoughts @LouisBrunner and @walker-j ?

**Comment by LouisBrunner** [comment]
I am fine with either, `duration` just makes it nicely backward-compatible, less potential issues and support from us?
