### ISSUE TITLE
[{'error': {'error_code': 3, 'title': "you don't own the robot lock"}}] when the arm is not locked

### ISSUE THREAD

**Issue by VasilyMorzhakov** [automata-tech/eva_python_sdk#54]
Strange state:

The arm is hanging in a state that seems senseless:

">>> eva.unlock()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aivero/.local/lib/python3.6/site-packages/evasdk/Eva.py", line 154, in unlock
    return self.__http_client.lock_unlock()
  File "/home/aivero/.local/lib/python3.6/site-packages/evasdk/eva_http_client.py", line 264, in lock_unlock
    eva_error('lock_unlock error', r)
  File "/home/aivero/.local/lib/python3.6/site-packages/evasdk/eva_errors.py", line 35, in eva_error
    __handle_http_error(label, r)
  File "/home/aivero/.local/lib/python3.6/site-packages/evasdk/eva_errors.py", line 54, in __handle_http_error
    raise EvaAdminError(error_string)
evasdk.eva_errors.EvaAdminError: lock_unlock error: status code 403 with error [{'error': {'error_code': 3, 'title': "you don't own the robot lock"}}]
>>> eva.lock_status()
{'owner': 'none', 'status': 'unlocked'}"

I don't see a way how to resolve this state by Python API.

**Comment by LouisBrunner** [comment]
Hi @VasilyMorzhakov,

Thank you for your report. It seems like you are trying to unlock the Robot while it is already unlocked, which we consider an error. Note that you can ignore that exception by catching it (`except evasdk.EvaError`), however we recommend you use `with eva.lock():` which provides you with a context which will manages the lock for you (see the second example here https://github.com/automata-tech/eva_python_sdk#examples).

If this doesn't address your issue, can you please provide more information about how the robot is "hanging" and in which state? A copy of your script or some reproducible example would allow us to help you quicker!

**Comment by VasilyMorzhakov** [comment]
The same error for the lock command. This was an example when I tried to unlock, hoping it could help.  All moving and IO commands were enclosured by "with lock", as you recommend. This situation is repeated sometimes. Looks as there's a pattern: we loose connection (http Exception), after restarting the app this error appears. Since the problem is repeated 1-2 times a week, I'll save log to share with you in a few days.

**Comment by LouisBrunner** [comment]
@VasilyMorzhakov,

It seems like you are running into several issues at the same time (identified thanks to your logs and support package):
 * When uploading a long toolpath, the SDK `toolpaths_use` endpoint times out, creating an exception and exiting the lock context
 * The toolpath upload is then cancelled leaving the backend in an incorrect state

While the latter can only be fixed through a software update (which we hope will be available soon), we can more easily fix the SDK to ensure you don't run into that issue again.

**Comment by VasilyMorzhakov** [comment]
Thanks for the response! We won't touch the arm in a week or two, so, please, consider the best option anyway.
