### ISSUE TITLE
Go_To mode change

### ISSUE THREAD

**Issue by UOHRobotics** [automata-tech/eva_python_sdk#56]
Hi there,

I was wondering how you change the mode from teach to automatic, I keep getting a unknown route error

Many thanks

JP

**Comment by LouisBrunner** [comment]
HI @UOHRobotics,

It depends on your SDK version. v1.0.0 correspond to a Choregraph 2.1.2 and earlier and don't support automatic/teach mode.

Using v2.0.0 and later of the SDK, which is compatible with Choreograph 3.0.0 and later, you should be able to use the following snippet:
```
eva = Eva(host_ip, token)

with eva.lock():
    eva.control_wait_for_ready()
    eva.control_go_to([0, 0, 0, 0, 0, 0], mode='automatic')
```

If you are running into any errors with that code, could you provide the code and the error that is raised?

**Comment by UOHRobotics** [comment]
Thank you for getting back to me,

In hindsight, yes the problem is that I am using choreograph 2.11. However i can not find any updates availible. The technical referance directs you to https://automata.tech. But I cant seem to find any software updates anyware. 

Thanks

JP

**Comment by LouisBrunner** [comment]
The updates are available here: https://automata.tech/updates/, the website explains how to download and apply an update. Don't hesitate to contact us if you are running into any issue with updating your robot (you can also reach our support through support@automata.tech).

I will forward your feedback about the difficulty to find the updates to the rest of the team, thank you!
