### ISSUE TITLE
Make `__globals_editing` public

### ISSUE THREAD

**Issue by LouisBrunner** [automata-tech/eva_python_sdk#67]
Currently, `EvaHTTPClient` doesn't expose `__globals_editing`. While `set_gpios` does cover all _current_ usages of that function, it does make it more difficult to extend in the future (when we add more properties).

We should make it accessible (from the `Eva` class as well) so we are a bit more future-proof.

**Comment by tallpress** [comment]
https://github.com/automata-tech/eva_python_sdk/pull/73
