### ISSUE TITLE
Problem using saved toolpaths

### ISSUE THREAD

**Issue by AirChord** [automata-tech/eva_python_sdk#68]
Hello, I'm a student that is currently using your robot controlled with the sdk for a project and trying to use a saved toolpath that my code can retrive without a problem but when it tries to use it the following error appear "eva_python_sdk.evasdk.eva_errors.EvaError: control_home error: status code 400 with error [{'error': {'error_code': 0, 'title': 'Toolpath error', 'details': 'Need a valid uploaded timeline to go home to'}}]"

My code:
with eva.lock():
        print("111111111111111111111")
        eva.control_wait_for_ready()
        print("2222222222222222222222")
        print(eva.toolpaths_retrieve(2))
        eva.toolpaths_use_saved(2)
        print(eva.toolpaths_retrieve(2))
        print("33333333333333333333333")
        eva.control_home()
        print("33333333333333333333333")
        eva.control_run(loop=1, wait_for_ready=True, mode='teach')
        print("44444444444444444444444")

Result:
111111111111111111111
2222222222222222222222
{'id': 2, 'name': 'linearTest', 'hash': 'd0cddfb482ef78e2c9de3f3c526e5810c11c67a858ef81d70bd2722da52cdbc2', 'toolpath': {'metadata': {'version': 2, 'default_max_speed': 0.2, 'next_label_id': 2, 'analog_modes': {'i0': 'voltage', 'i1': 'voltage', 'o0': 'voltage', 'o1': 'voltage'}, 'payload': 0}, 'waypoints': [{'joints': [1.5708443, -0.5594407, -2.561251, 1.5697896, -0.0015340276, 0.00067113707], 'label_id': 0}, {'joints': [1.1056981, -0.56795806, -2.544969, 0.7791705, -0.015099977, 0.32628042], 'label_id': 1}], 'timeline': [{'type': 'home', 'waypoint_id': 0}, {'type': 'trajectory', 'trajectory': 'linear', 'waypoint_id': 1}]}}
{'id': 2, 'name': 'linearTest', 'hash': 'd0cddfb482ef78e2c9de3f3c526e5810c11c67a858ef81d70bd2722da52cdbc2', 'toolpath': {'metadata': {'version': 2, 'default_max_speed': 0.2, 'next_label_id': 2, 'analog_modes': {'i0': 'voltage', 'i1': 'voltage', 'o0': 'voltage', 'o1': 'voltage'}, 'payload': 0}, 'waypoints': [{'joints': [1.5708443, -0.5594407, -2.561251, 1.5697896, -0.0015340276, 0.00067113707], 'label_id': 0}, {'joints': [1.1056981, -0.56795806, -2.544969, 0.7791705, -0.015099977, 0.32628042], 'label_id': 1}], 'timeline': [{'type': 'home', 'waypoint_id': 0}, {'type': 'trajectory', 'trajectory': 'linear', 'waypoint_id': 1}]}}
33333333333333333333333
Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 1019, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "evaAquisitionStop.py", line 87, in datagram_received
    ReceivedMessage(socket=self.transport, message=data)
  File "evaAquisitionStop.py", line 127, in ReceivedMessage
    EvaStartMovement()
  File "evaAquisitionStop.py", line 183, in EvaStartMovement
    eva.control_home()
  File "/home/muser/see2pick/see2pick.git/eva/eva_python_sdk/evasdk/Eva.py", line 184, in control_home
    return self.__http_client.control_home(wait_for_ready=wait_for_ready)
  File "/home/muser/see2pick/see2pick.git/eva/eva_python_sdk/evasdk/eva_http_client.py", line 336, in control_home
    eva_error('control_home error', r)
  File "/home/muser/see2pick/see2pick.git/eva/eva_python_sdk/evasdk/eva_errors.py", line 35, in eva_error
    __handle_http_error(label, r)
  File "/home/muser/see2pick/see2pick.git/eva/eva_python_sdk/evasdk/eva_errors.py", line 56, in __handle_http_error
    raise EvaError(error_string)
eva_python_sdk.evasdk.eva_errors.EvaError: control_home error: status code 400 with error [{'error': {'error_code': 0, 'title': 'Toolpath error', 'details': 'Need a valid uploaded timeline to go home to'}}]

**Comment by LouisBrunner** [comment]
Hello @AirChord,

Thank you for your report, I will need the following information to be able to help you:
 - Version of the SDK you are using
 - Version of the Eva you are using
 - A support log exported from the "Config" page just after you run into this error
 - Bonus: if you can give me a repo which can reproduce the issue (including the toolpath), that would speed up things greatly

**Comment by AirChord** [comment]
Hello 
I' m using SDK 2.0.0 and the robot as the version 3.0.1.
Actually I have done one workaround, on the next day that I publish this issue, I send the robot to go one more millimeter and it worked.
I cant give you the repository because its already worked much more and even I cant reproduce the error in the same conditions.
I now have one problem that is concerning that is a clicking noise is doing every time it moves, because it was almost new (just unboxing and testing if it works) and I was the one that is making work almost 24/7, and after almost 1 and half hour of continuous work it stops and I need to wait and restart it pressing the ON/OFF button.
I have a video of it making the noise that I send attached, and a text file with the output given on the console when it stops suddenly.

Thank you.
[ClickingNoise.zip](https://github.com/automata-tech/eva_python_sdk/files/5511359/ClickingNoise.zip)

**Comment by AirChord** [comment]
After downloading the support export file (attached), and after a brief analysis I detected this information on the file "eva_brain.log"
"[2020-11-14T09:55:28] [ERROR] [c/hardware/HardwareGateway.cpp:2623] [Hard] Servo 6: Motor hall effect sensor error"
I don't if this helps.

Best regards.
[support_Loyal Sydney Ranger_2020-11-14T09-56-07Z.zip](https://github.com/automata-tech/eva_python_sdk/files/5512136/support_Loyal.Sydney.Ranger_2020-11-14T09-56-07Z.zip)

**Comment by LouisBrunner** [comment]
@AirChord,

This sounds like a mechanical issue, please contact support@automata.tech directly.
