### ISSUE TITLE
Use x,y,z coordinates

### ISSUE THREAD

**Issue by Rothusar** [automata-tech/eva_python_sdk#69]
Hello together,
So far I've only worked with Choreograph, and now I've started programming with Python. 

Now I have a few questions, how can I use coordinates with X, Y, Z?
eva.control_go_to([0, 0, 0, 0, 0, 0], mode='teach')  
Am I correct that these positions are joint_angles?

What Eva should make: I have a Stack and EVA should take the top piece of a stack and lay this piece in a other machine.
The part is 8 mm thick, that means next time eva should go down 8 mm from the last position. 
I can't solve the problem with the choreograph unless I make  400 waypoints by hand.

**Comment by LouisBrunner** [comment]
Hi @Rothusar,

Choreograph currently supports 2D grids which allow you to do this kind of use cases, however you can't do a 1D stack yet.

In the meantime, you can use the [Inverse Kinematics](https://automata.tech/docs/v/4.0.0/api/calculation/#inverse-kinematics) function to calculate the joint angles for a given X, Y, Z coordinate.
