### ISSUE TITLE
calc_nudge does not return result like other calc functions

### ISSUE THREAD

**Issue by euanwm** [automata-tech/eva_python_sdk#96]
calc_nudge when called does not return the success result and joint angles similar to that of other IK functions. It only returns the angles themselves.

**Comment by LouisBrunner** [comment]
That should be fixed in the latest development, maybe give it a try to make sure?

**Comment by euanwm** [comment]
https://github.com/automata-tech/eva_python_sdk/blob/development/evasdk/eva_http_client.py#L546

Will only be a minor change to remove the ['joints'] part and to update the docstring.

**Comment by euanwm** [comment]
Checked development branch. Everything is aligned. Will update docstrings on Eva.py prior to next release.
